server:
  port: 7077
spring:
  application:
    name: sszh-server-order
  boot:
    admin:
      client:
        url: http://127.0.0.1:9000  #申明SBA的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@127.0.0.1:7075/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true                                       #将IP注册到服务注册中心

#放开所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'