#Redis配置
unionpay:
  redis:
    hosts: 172.18.75.66:6379
    maxIdle: 50
    maxWait: 1000
    maxTotal: 100
    minIdle: 5
    maxWaitMillis: 60000
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true