package com.sszh.mybatis.example.internal;

import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.api.dom.java.InnerClass;
import org.mybatis.generator.internal.DefaultCommentGenerator;

/**
 * 自定义生成注解的类
 */
public class CustomCommentGenerator extends DefaultCommentGenerator {

    
    @Override
    public void addClassComment(InnerClass innerClass, IntrospectedTable introspectedTable, boolean markAsDoNotDelete) {
        StringBuilder sb = new StringBuilder();
        innerClass.addJavaDocLine("/**");
        innerClass.addJavaDocLine(" * This class was generated by MyBatis Generator.");
        sb.append(" * This class corresponds to the database table ");
        sb.append(introspectedTable.getFullyQualifiedTable());
        innerClass.addJavaDocLine(sb.toString());
        this.addJavadocTag(innerClass, markAsDoNotDelete);
        innerClass.addJavaDocLine(" */");
    }
    
//    
//    public void addClassComment(InnerClass innerClass, IntrospectedTable introspectedTable, boolean markAsDoNotDelete) {
//        // 添加表名注释
//        String remark = introspectedTable.getRemarks();
//        System.out.println(remark);
//        innerClass.addJavaDocLine("/**");
//        innerClass.addJavaDocLine(" * " + remark + "-实体类");
//        innerClass.addJavaDocLine(" */");
//    }
    
    @Override
    public void addFieldComment(Field field, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn) {
        // 添加字段注释
        String remark = introspectedColumn.getRemarks();
        System.out.println(field.getName() + "    " + introspectedColumn.getRemarks());
        if (remark != null && remark.trim().length()>0){
            field.addJavaDocLine("/**");
            field.addJavaDocLine(" * " + introspectedColumn.getRemarks());
            field.addJavaDocLine(" */");
        }
    }
    
}
